---
# tasks file for ansible-wal-g
- name: wal-g | check binary installed
  stat:
    path: "{{ walg_binary_path }}"
  register: walg_current_binary
  changed_when: false

- name: wal-g | get current binary version
  shell: |
    set -o pipefail
    sudo -Hu nobody timeout 2 {{ walg_binary_path }} --version 2>&1 | grep -Eoi '([0-9]{1,}\.){1,3}[0-9]{1,}(|-[a-z0-9\.]{1,})' | sort -uV | head -1
  args:
    executable: /bin/bash
  register: walg_current_version
  changed_when: false
  check_mode: false
  when:
    - walg_current_binary.stat.exists

- name: wal-g | download with unarchive when upgrade or downgrade
  unarchive:
    src: "{{ walg_url }}"
    dest: "{{ walg_binary_path | dirname }}"
    exclude:
      - 'README.md'
      - 'LICENSE'
    remote_src: true
    force: true
    owner: root
    group: root
    mode: 0755
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')
